const vi = {
    "accept": "Đồng ý",
    "addRule": "Thêm quy tắc",
    "am": "Sáng",
    "apply": "Áp dụng",
    "cancel": "Hủy bỏ",
    "choose": "Chọn",
    "chooseDate": "Chọn ngày",
    "chooseMonth": "Chọn tháng",
    "chooseYear": "Chọn năm",
    "clear": "Xóa",
    "completed": "Hoàn thành",
    "contains": "Chứa",
    "custom": "Tùy chỉnh",
    "dateAfter": "Ngày sau",
    "dateBefore": "Ngày trước",
    "dateFormat": "dd/mm/yy",
    "dateIs": "Ngày là",
    "dateIsNot": "Ngày không phải là",
    "dayNames": [
      "Chủ Nhật",
      "Thứ Hai",
      "Thứ Ba",
      "Thứ Tư",
      "Thứ Năm",
      "Thứ Sáu",
      "Thứ Bảy"
    ],
    "dayNamesMin": [
      "CN",
      "T2",
      "T3",
      "T4",
      "T5",
      "T6",
      "T7"
    ],
    "dayNamesShort": [
      "CN",
      "T2",
      "T3",
      "T4",
      "T5",
      "T6",
      "T7"
    ],
    "emptyFilterMessage": "Không tìm thấy kết quả nào",
    "emptyMessage": "Không có tùy chọn khả dụng",
    "emptySearchMessage": "Không tìm thấy kết quả nào",
    "emptySelectionMessage": "Chưa chọn mục nào",
    "endsWith": "Kết thúc bằng",
    "equals": "Bằng",
    "fileSizeTypes": [
      "B",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    "filter": "Lọc",
    "firstDayOfWeek": 1,
    "gt": "Lớn hơn",
    "gte": "Lớn hơn hoặc bằng",
    "lt": "Nhỏ hơn",
    "lte": "Nhỏ hơn hoặc bằng",
    "matchAll": "Phù hợp tất cả",
    "matchAny": "Phù hợp bất kỳ",
    "medium": "Trung bình",
    "monthNames": [
      "Tháng 1",
      "Tháng 2",
      "Tháng 3",
      "Tháng 4",
      "Tháng 5",
      "Tháng 6",
      "Tháng 7",
      "Tháng 8",
      "Tháng 9",
      "Tháng 10",
      "Tháng 11",
      "Tháng 12"
    ],
    "monthNamesShort": [
      "T1",
      "T2",
      "T3",
      "T4",
      "T5",
      "T6",
      "T7",
      "T8",
      "T9",
      "T10",
      "T11",
      "T12"
    ],
    "nextDecade": "Thập kỷ sau",
    "nextHour": "Giờ tiếp theo",
    "nextMinute": "Phút tiếp theo",
    "nextMonth": "Tháng sau",
    "nextSecond": "Giây tiếp theo",
    "nextYear": "Năm sau",
    "noFilter": "Không có bộ lọc",
    "notContains": "Không chứa",
    "notEquals": "Không bằng",
    "now": "Bây giờ",
    "passwordPrompt": "Vui lòng nhập mật khẩu",
    "pending": "Đang chờ xử lý",
    "pm": "Chiều",
    "prevDecade": "Thập kỷ trước",
    "prevHour": "Giờ trước",
    "prevMinute": "Phút trước",
    "prevMonth": "Tháng trước",
    "prevSecond": "Giây trước",
    "prevYear": "Năm trước",
    "reject": "Từ chối",
    "removeRule": "Xóa quy tắc",
    "searchMessage": "Đã tìm thấy {0} kết quả",
    "selectionMessage": "Đã chọn {0} mục",
    "showMonthAfterYear": false,
    "startsWith": "Bắt đầu với",
    "strong": "Mạnh",
    "today": "Hôm nay",
    "upload": "Tải lên",
    "weak": "Yếu",
    "weekHeader": "Tuần",
    "aria": {
      "cancelEdit": "Hủy chỉnh sửa",
      "close": "Đóng",
      "collapseLabel": "Thu gọn",
      "collapseRow": "Thu gọn hàng",
      "editRow": "Chỉnh sửa hàng",
      "expandLabel": "Mở rộng",
      "expandRow": "Mở rộng hàng",
      "falseLabel": "Sai",
      "filterConstraint": "Ràng buộc bộ lọc",
      "filterOperator": "Toán tử lọc",
      "firstPageLabel": "Trang đầu",
      "gridView": "Xem dạng lưới",
      "hideFilterMenu": "Ẩn menu lọc",
      "jumpToPageDropdownLabel": "Chuyển đến trang (dropdown)",
      "jumpToPageInputLabel": "Nhập số trang",
      "lastPageLabel": "Trang cuối",
      "listView": "Xem danh sách",
      "moveAllToSource": "Chuyển tất cả về nguồn",
      "moveAllToTarget": "Chuyển tất cả sang đích",
      "moveBottom": "Chuyển xuống cuối",
      "moveDown": "Chuyển xuống",
      "moveTop": "Chuyển lên đầu",
      "moveToSource": "Chuyển về nguồn",
      "moveToTarget": "Chuyển đến đích",
      "moveUp": "Chuyển lên",
      "navigation": "Điều hướng",
      "next": "Tiếp",
      "nextPageLabel": "Trang tiếp theo",
      "nullLabel": "Không được chọn",
      "otpLabel": "Nhập mã OTP {0}",
      "pageLabel": "Trang {page}",
      "passwordHide": "Ẩn mật khẩu",
      "passwordShow": "Hiển thị mật khẩu",
      "previous": "Trước",
      "previousPageLabel": "Trang trước",
      "removeLabel": "Xóa",
      "rotateLeft": "Xoay trái",
      "rotateRight": "Xoay phải",
      "rowsPerPageLabel": "Số hàng mỗi trang",
      "saveEdit": "Lưu chỉnh sửa",
      "scrollTop": "Cuộn lên đầu",
      "selectAll": "Chọn tất cả",
      "selectLabel": "Chọn",
      "selectRow": "Chọn hàng",
      "showFilterMenu": "Hiển thị menu lọc",
      "slide": "Trang chiếu",
      "slideNumber": "Trang {slideNumber}",
      "star": "1 sao",
      "stars": "{stars} sao",
      "trueLabel": "Đúng",
      "unselectAll": "Bỏ chọn tất cả",
      "unselectLabel": "Bỏ chọn",
      "unselectRow": "Bỏ chọn hàng",
      "zoomImage": "Phóng to hình ảnh",
      "zoomIn": "Phóng to",
      "zoomOut": "Thu nhỏ"
    }
  };
  
  export default vi;
  