export const DM_DONVI = {
  id: null,
  dm_donvi_id: null,
  loai_don_vi: null,
  ma: null,
  ten: null,
  trang_thai: null,
  sap_xep: null,
  ghi_chu: null,
  ngay_tao: null,
  nguoi_tao: null,
  ngay_cap_nhat: null,
  nguoi_cap_nhat: null,
  cap_so: null,
  cap_ma: null,
  dm_tinhthanh_id: null,
  dm_quanhuyen_id: null,
  dm_donvi_chuquan_id: null,
  ma_fmis: null,
  db_madonvi: null,
  db_madonvi_fmis: null,
  db_ngay: null,
  type_donvi: null,
  group_donvi: null,
  do_duthao: null,
  su_dung: null,
  ma_dviqly: null
};