const QLTN_YCTN = {
    id: null,
    ten_yctn: null,
    ma_yctn: null,
    ma_loai_yctn: null,
    tong_gia_tri: null,
    id_khach_hang: null,
    ma_khach_hang: null,
    loai_tai_san: null,
    crr_step: null,
    next_step: null,
    nam_thuc_hien: null,
    noi_dung: null,
    gtdt_truoc_thue: 0,
    gtdt_thue: 0,
    gtdt_sau_thue: 0,
    gtdt_chiet_giam: 0,
    gtdt_sau_chiet_giam: 0,
    ngay_ky_hop_dong: null,
    ngay_xay_ra_su_co: null,
    file_upload: null,
    ngay_giao_nv: null,
    file_dinh_kem_giao_nv: null,
    nguoi_giao_nhiem_vu: null,
    file_pa_thi_cong: null,
    nguoi_th_ks_lap_pa_thi_cong: null,
    ngay_nhap_kl_thuc_hien: null,
    nguoi_nhap_kl_thuc_hien: null,
    nguoi_ban_giao: null,
    don_vi_nhan_ban_giao: null,
    ngay_ban_giao: null,
    ghi_chu_ban_giao: null,
    phan_tram_thue: 0,
    phan_tram_chiet_giam: 0,
    ngay_ks_lap_pa_thi_cong: null,
    ngay_tao: new Date(),
    don_vi_thuc_hien: null
}

export default QLTN_YCTN;